#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png
SCREENSHOT="scrot -z $PICTURE"

BLUR="5x4"

$SCREENSHOT
convert $PICTURE -blur $BLUR $PICTURE
# magick $PICTURE -blur $BLUR $PICTURE
setxkbmap -layout us
i3lock -i $PICTURE
rm $PICTURE
